config/routes.rb
Rails.application.routes.draw do
  root "demons#index"
  resources :demons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/demon.rb
class Demon < ApplicationRecord

  validates :name, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :image_url, presence: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demons_controller.rb
class DemonsController < ApplicationController
  
  def index
    @demons = Demon.all
  end

  def show
    @demon = Demon.find(params[:id])
  end

  def new
    @demon = Demon.new
  end

  def create
    @demon = Demon.new(demon_params)

    if @demon.save
      redirect_to @demon
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @demon = Demon.find(params[:id])
  end

  def update
    @demon = Demon.find(params[:id])

    if @demon.update(demon_params)
      redirect_to @demon
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @demon = Demon.find(params[:id])
    @demon.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def demon_params
      params.require(:demon).permit(:name, :title, :description, :image_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demons_helper.rb
module DemonsHelper
end

app/views/demons/_form.html.erb
<%= form_with model: demon do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% demon.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :title %><br>
    <%= form.text_area :title %><br>
    <% demon.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% demon.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.text_area :image_url %><br>
    <% demon.errors.full_messages_for(:image_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/demons/edit.html.erb
<h1>Edit Demon!</h1>

<%= render "form", demon: @demon %>
<li><a href="#" onclick="history.back()">Back to Demon?</a></li>
<li><%= link_to "Back to all Demonzz", demons_path(@demon) %></li>

app/views/demons/index.html.erb
<h1>All Demons</h1>

<%= link_to "Create New Demon!", new_demon_path %>
<hr />

<ul>
  <% @demons.each do |demon| %>
    </li>
    <img src="<%= demon.image_url %>" width="300" height="300">
    <li>
      <%= link_to demon.name, demon %>
      </a>
    <hr />
  <% end %>
</ul>

app/views/demons/new.html.erb
<h1>Add A New Demon!</h1>

<h1>New Article</h1>

<%= render "form", demon: @demon %>

app/views/demons/show.html.erb
<h1><%= @demon.name %></h1>
  <img src="<%= @demon.image_url %>" width="300" height="300">
  
  <p><h4> <strong>Title:</strong> <%= @demon.title %></p>
  <p><h4>Description:</h4></p>
  <p><%= @demon.description %></p>
  
<ul>
  <li><%= link_to "Edit This Demon", edit_demon_path(@demon) %></li>
  <li><%= link_to "Destroy This Demon", demon_path(@demon), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to "Back to all Demonzz", demons_path(@demon) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Collect All The Demons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  

  <body>
    <%= yield %>
  </body>
</html>

<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>